#include "DMGameplayTagAccessorGenerator.h"

#include "Engine/DataTable.h"
#include "GameplayTagsManager.h"
#include "GameplayTagsSettings.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"

#define LOCTEXT_NAMESPACE "FDMGameplayTagAccessorGenerator"

namespace
{
	const TCHAR* BeginMarker = TEXT("// BEGIN AUTO-GENERATED GAMEPLAY TAG TABLE ACCESSORS");
	const TCHAR* EndMarker = TEXT("// END AUTO-GENERATED GAMEPLAY TAG TABLE ACCESSORS");
}

bool FDMGameplayTagAccessorGenerator::Generate(FText& OutMessage)
{
	TArray<FCollectedTag> Tags;
	if (!CollectTags(Tags, OutMessage))
	{
		return false;
	}

	if (Tags.IsEmpty())
	{
		OutMessage = LOCTEXT("NoGameplayTagsFound", "No GameplayTag rows were found in GameplayTagTableList.");
		return false;
	}

	return WriteHeader(Tags, OutMessage);
}

bool FDMGameplayTagAccessorGenerator::CollectTags(TArray<FCollectedTag>& OutTags, FText& OutMessage)
{
	const UGameplayTagsSettings* Settings = GetDefault<UGameplayTagsSettings>();
	if (!Settings)
	{
		OutMessage = LOCTEXT("MissingGameplayTagSettings", "Unable to read GameplayTagsSettings.");
		return false;
	}

	TMap<FName, FCollectedTag> TagsByName;

	for (const FSoftObjectPath& TablePath : Settings->GameplayTagTableList)
	{
		if (!TablePath.IsValid())
		{
			continue;
		}

		UDataTable* DataTable = Cast<UDataTable>(TablePath.TryLoad());
		if (!DataTable)
		{
			OutMessage = FText::Format(
				LOCTEXT("LoadTableFailed", "Unable to load GameplayTag table: {0}"),
				FText::FromString(TablePath.ToString()));
			return false;
		}

		TArray<FGameplayTagTableRow*> Rows;
		DataTable->GetAllRows<FGameplayTagTableRow>(TEXT("DMToolBox Generate GameplayTags"), Rows);

		for (const FGameplayTagTableRow* Row : Rows)
		{
			if (!Row || Row->Tag.IsNone())
			{
				continue;
			}

			FCollectedTag& CollectedTag = TagsByName.FindOrAdd(Row->Tag);
			CollectedTag.TagName = Row->Tag;
			if (CollectedTag.DevComment.IsEmpty())
			{
				CollectedTag.DevComment = Row->DevComment;
			}
			if (CollectedTag.SourceTable.IsEmpty())
			{
				CollectedTag.SourceTable = TablePath.GetAssetName();
			}
		}
	}

	TagsByName.GenerateValueArray(OutTags);
	OutTags.Sort([](const FCollectedTag& A, const FCollectedTag& B)
	{
		return A.TagName.LexicalLess(B.TagName);
	});

	return true;
}

bool FDMGameplayTagAccessorGenerator::WriteHeader(const TArray<FCollectedTag>& Tags, FText& OutMessage)
{
	const FString HeaderPath = FPaths::ConvertRelativePathToFull(
		FPaths::Combine(FPaths::ProjectDir(), TEXT("Source/NoOutsiders/Define/NOGameplayTag.h")));

	FString HeaderContent;
	if (!FFileHelper::LoadFileToString(HeaderContent, *HeaderPath))
	{
		OutMessage = FText::Format(LOCTEXT("LoadHeaderFailed", "Unable to load header: {0}"), FText::FromString(HeaderPath));
		return false;
	}

	const FString GeneratedBlock = BuildGeneratedBlock(Tags);
	if (!ReplaceOrAppendGeneratedBlock(HeaderContent, GeneratedBlock))
	{
		OutMessage = LOCTEXT("ReplaceBlockFailed", "Unable to replace generated GameplayTag accessor block.");
		return false;
	}

	if (!FFileHelper::SaveStringToFile(HeaderContent, *HeaderPath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
	{
		OutMessage = FText::Format(LOCTEXT("SaveHeaderFailed", "Unable to save header: {0}"), FText::FromString(HeaderPath));
		return false;
	}

	OutMessage = FText::Format(LOCTEXT("GenerateSuccess", "Generated {0} GameplayTags in NOGameplayTag.h."), FText::AsNumber(Tags.Num()));
	return true;
}

FString FDMGameplayTagAccessorGenerator::BuildGeneratedBlock(const TArray<FCollectedTag>& Tags)
{
	FString Block;
	Block += FString::Printf(TEXT("%s\n"), BeginMarker);
	Block += TEXT("// Generated by DMToolBox from Project Settings > Gameplay Tags > GameplayTagTableList.\n");
	Block += TEXT("// Keep manual Native GameplayTag declarations outside this block.\n");
	Block += TEXT("namespace NODataTableGameplayTags\n");
	Block += TEXT("{\n");

	TSet<FString> UsedNames;
	for (const FCollectedTag& Tag : Tags)
	{
		const FString AccessorName = BuildAccessorName(Tag.TagName, UsedNames);
		const FString Comment = SanitizeComment(Tag.DevComment);
		if (!Comment.IsEmpty())
		{
			Block += FString::Printf(TEXT("\t/** %s */\n"), *Comment);
		}
		Block += FString::Printf(TEXT("\tinline FGameplayTag %s()\n"), *AccessorName);
		Block += TEXT("\t{\n");
		Block += FString::Printf(TEXT("\t\tstatic const FGameplayTag Tag = FGameplayTag::RequestGameplayTag(TEXT(\"%s\"));\n"), *Tag.TagName.ToString());
		Block += TEXT("\t\treturn Tag;\n");
		Block += TEXT("\t}\n\n");
	}

	Block += TEXT("}\n");
	Block += FString::Printf(TEXT("%s"), EndMarker);
	return Block;
}

FString FDMGameplayTagAccessorGenerator::BuildAccessorName(const FName TagName, TSet<FString>& UsedNames)
{
	FString Result;
	for (const TCHAR Character : TagName.ToString())
	{
		Result.AppendChar(FChar::IsAlnum(Character) ? Character : TEXT('_'));
	}

	while (Result.Contains(TEXT("__")))
	{
		Result.ReplaceInline(TEXT("__"), TEXT("_"));
	}

	Result.RemoveFromStart(TEXT("_"));
	Result.RemoveFromEnd(TEXT("_"));

	if (Result.IsEmpty() || FChar::IsDigit(Result[0]))
	{
		Result = FString::Printf(TEXT("Tag_%s"), *Result);
	}

	const FString BaseName = Result;
	int32 Suffix = 2;
	while (UsedNames.Contains(Result))
	{
		Result = FString::Printf(TEXT("%s_%d"), *BaseName, Suffix++);
	}

	UsedNames.Add(Result);
	return Result;
}

FString FDMGameplayTagAccessorGenerator::SanitizeComment(const FString& Comment)
{
	FString Result = Comment;
	Result.ReplaceInline(TEXT("*/"), TEXT("* /"));
	Result.ReplaceInline(TEXT("\r"), TEXT(" "));
	Result.ReplaceInline(TEXT("\n"), TEXT(" "));
	return Result.TrimStartAndEnd();
}

bool FDMGameplayTagAccessorGenerator::ReplaceOrAppendGeneratedBlock(FString& FileContent, const FString& GeneratedBlock)
{
	const int32 BeginIndex = FileContent.Find(BeginMarker, ESearchCase::CaseSensitive);
	const int32 EndIndex = FileContent.Find(EndMarker, ESearchCase::CaseSensitive);

	if (BeginIndex != INDEX_NONE || EndIndex != INDEX_NONE)
	{
		if (BeginIndex == INDEX_NONE || EndIndex == INDEX_NONE || EndIndex < BeginIndex)
		{
			return false;
		}

		const int32 ReplaceEnd = EndIndex + FCString::Strlen(EndMarker);
		FileContent = FileContent.Left(BeginIndex) + GeneratedBlock + FileContent.Mid(ReplaceEnd);
		return true;
	}

	FileContent.TrimEndInline();
	FileContent += TEXT("\n\n");
	FileContent += GeneratedBlock;
	FileContent += TEXT("\n");
	return true;
}

#undef LOCTEXT_NAMESPACE
